export const animeProtagonists = [
  "Naruto Uzumaki",
  "Monkey D. Luffy",
  "Ichigo Kurosaki",
  "Goku",
  "Eren Yeager",
  "Light Yagami",
  "Edward Elric",
  "Tanjiro Kamado",
  "Izuku Midoriya",
  "Yuji Itadori",
  "Saitama",
  "Kenshin Himura",
  "Gon Freecss",
  "Killua Zoldyck",
  "Lelouch Lamperouge",
  "Natsu Dragneel",
  "Asta",
  "Meliodas",
  "Kaneki Ken",
  "Shinji Ikari",
  "Spike Spiegel",
  "Vash the Stampede",
  "Thorfinn",
  "Denji",
  "Subaru Natsuki",
  "Kirito",
  "Asuna Yuuki",
  "Inuyasha",
  "Yusuke Urameshi",
  "Mob",
  "Reigen Arataka",
  "Ash Ketchum",
  "Joestar Jonathan",
  "Joseph Joestar",
  "Jotaro Kujo",
  "Josuke Higashikata",
  "Giorno Giovanna",
  "Gintoki Sakata",
  "Rintarou Okabe",
  "Senku Ishigami",
  "Hyakkimaru",
  "Alucard",
  "Akira Fudo",
  "Simon",
  "Kamina",
  "Shoyo Hinata",
  "Kageyama Tobio",
  "Ippo Makunouchi",
  "Sakura Kinomoto",
  "Usagi Tsukino",
  "Soma Yukihira",
  "Erza Scarlet",
  "Mikasa Ackerman",
  "Armin Arlert",
  "Boruto Uzumaki",
  "Tatsumi",
  "Esdeath",
  "Rimuru Tempest",
  "Naofumi Iwatani",
  "Kazuma Satou",
  "Shigeo Kageyama",
  "Hachiman Hikigaya",
  "Oreki Houtarou",
  "Zero Two",
  "Shiro",
  "Sora",
  "Ichimatsu",
  "Osomatsu",
  "Deku",
  "Black Star",
  "Maka Albarn",
  "Allen Walker",
  "Koro Sensei",
  "Akame",
  "Tanjirou Kamado",
  "Yato",
  "Nagisa Shiota",
  "Shinra Kusakabe",
  "Lain Iwakura",
  "Tomoya Okazaki",
  "Taichi Yagami",
  "Takemichi Hanagaki",
  "Draken",
  "Mikey",
  "Aang",
  "Korra",
  "Arata Kaizaki",
  "Chisaki Hiradaira",
  "Violet Evergarden",
  "Mash Burnedead",
  "Frieren"
];
